```{r library}

library(readxl)
library(bruceR)
library(patchwork)
library(gridExtra)
library(dplyr)
library(ggpattern)

```


# Directory
```{r data directory}

data_dir <- file.path("..", "figs_data", "EXP2-2_CMPD_condilevel_data_260121.xlsx")
```

# General Parameter
```{r parameter}
pt_to_mm <- 0.57
mm_to_pt <- 2.8346

width_in_inches <- 25
height_in_inches <- 25

x_start <- 0.4
bar_width <- 0.3

title_size <- 100
text_size <- 100
text_x_size <- 90
title_margin <- 35
text_margin <- 35

legend_size <- 46

sig_size <- 20
sig_ns_size <- 40
sig_seg_size <- 2

bar_linewidth <- 3

```

# Allocation
```{r EXP3_PMPD Allocation}
# 读取 Excel 文件
data <- read_excel(data_dir, sheet = 'Allocation')


#### 提取risky下三个情境的Gratitude/Allocation
exp_data <- data[data$Outcome_d == 'HigherOutcome',]

tmp_data <- data[data$Outcome_d == 'LowerOutcome',]
exp_data <- rbind(exp_data, tmp_data)

# tmp_data <- data[data$Outcome == 'Uncertain',]
# exp_data <- rbind(exp_data, tmp_data)
####

### one-factor ANOVA
print('【Exp3】')

# 使用tapply计算平均值和标准差
means <- tapply(exp_data$Value, list(exp_data$Outcome_raw, exp_data$Situation_raw), mean)
std_devs <- tapply(exp_data$Value, list(exp_data$Outcome_raw, exp_data$Situation_raw), sd)
cat("Means:", means, '\n')
cat("Standard Deviations:", std_devs, '\n')

```

```{r}
# 执行单因素方差分析
MANOVA(
  exp_data, dv = "Value", subID = "SubID", within = c("Outcome_raw","Situation_raw"), sph.correction = 'GG') %>%
  EMMEANS(effect = "Outcome_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Situation_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Outcome_raw", by = "Situation_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Situation_raw", by = "Outcome_raw", p.adjust = "bonferroni")

```

## fig-Allocation
```{r, echo=TRUE}
f_outcome_fill <- c(
  "Outcome2" = "#D6E6F5",
  "Outcome3" = "#DCEBDD",
  "Outcome4" = "#E6E8C8",
  "Outcome6" = "#F1D8B8",
  "Outcome7" = "#F2BE9E",
  "Outcome8" = "#E99A78"
)

f_outcome_edge <- c(
  "Outcome2" = "#4F81BD",
  "Outcome3" = "#6FA56F",
  "Outcome4" = "#9BA96A",
  "Outcome6" = "#C79A5A",
  "Outcome7" = "#D9845F",
  "Outcome8" = "#E76F51"
)



legend_y <- 78
legend_x1 <- 1.25
legend_x2 <- 3.65

legend_box_w <- 0.42
legend_box_h <- 4.0
legend_text_gap <- 0.2
legend_text_size <- legend_size / 2.4

legend_line_offset_1 <- 0.04
legend_line_offset_2 <- 0.20
legend_line_w <- 0.18
legend_line_y <- 1.45

exp_data$Outcome_raw <- factor(exp_data$Outcome_raw, 
                        levels = c("Outcome2","Outcome3", "Outcome4","Outcome6","Outcome7","Outcome8"))
exp_data$Situation_raw <- factor(exp_data$Situation_raw, levels = c("Uncertain", "Certain"))

# 先分开处理两个组的数据
df_u <- subset(exp_data, Situation_raw == "Uncertain")
df_c <- subset(exp_data, Situation_raw == "Certain")


exp_data$x_pos = as.numeric(exp_data$Outcome_raw) + ifelse(exp_data$Situation_raw == "Uncertain", -drift, drift)

summary_data_all <- exp_data %>%
  group_by(Situation_raw, Outcome_raw) %>%
  summarize(
    mean_value = mean(Value, na.rm = TRUE),
    se = sd(Value, na.rm = TRUE) / sqrt(sum(!is.na(Value))),
    .groups = "drop"
  ) %>%
  mutate(
    x_pos = as.numeric(Outcome_raw) +
      ifelse(Situation_raw == "Uncertain", -drift, drift)
  )

summary_data_all$fill_color <- NA

summary_data_all$fill_color[
  summary_data_all$Situation_raw == "Uncertain"
] <- uncertain_palette[
  as.character(
    summary_data_all$Outcome_raw[
      summary_data_all$Situation_raw == "Uncertain"
    ]
  )
]

summary_data_all$fill_color[
  summary_data_all$Situation_raw == "Certain"
] <- certain_palette[
  as.character(
    summary_data_all$Outcome_raw[
      summary_data_all$Situation_raw == "Certain"
    ]
  )
]

sig1_y <- 70
sig2_y <- 70
sig3_y <- 74
sig_seg_margin <- 0.6
sig_interval <- 0.02
sig_height <- 1

drift <- 0.18

pattern_angle <- 45
pattern_density <- 0.40
pattern_spacing <- 0.07
pattern_size <- 0.20

p2 <- ggplot() +
  geom_col(
  data = summary_data_all,
  aes(
    x = x_pos,
    y = mean_value,
    fill = fill_color
  ),
  width = bar_width,
  color = NA
 ) +
  
  # geom_point(
  #   data = exp_data,
  #   aes(x = x_pos, group = Outcome_raw, y = Value, color = Outcome_raw),
  #   size = point_size,
  #   alpha = point_alpha,
  #   position = position_dodge(bar_width),
  #   show.legend = FALSE
  # ) +

  geom_errorbar(
    data = summary_data_all,
    aes(
      x = x_pos,
      ymin = mean_value - se,
      ymax = mean_value + se
    ),
    width = 0.1,
    linewidth = 1.5
  ) +
  scale_fill_identity() +
  # scale_color_manual(values = outcome_palette, guide = "none") +
  # scale_pattern_fill_manual(values = outcome_palette, guide = "none") +
  # scale_pattern_colour_manual(values = outcome_palette, guide = "none") +

  # scale_pattern_manual(
  #   values = c(
  #     "Uncertain" = "none",
  #     "Certain" = "stripe"
  #   ),
  #   name = NULL
  # ) +


  xlab("Outcome") +
  ylab("Allocation") +

  theme_classic(base_family = "Arial") +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.justification = "center",
    legend.title = element_blank(),
    legend.text = element_text(size = legend_size, color = "black"),
    legend.key.width = unit(1.2, "cm"),
    legend.key.height = unit(0.45, "cm"),
    legend.box.margin = margin(b = 4),

    axis.title.x = element_text(size = title_size, margin = margin(t = title_margin)),
    axis.text.x = element_text(size = text_x_size, margin = margin(t = text_margin)),
    axis.title.y = element_text(size = title_size, margin = margin(r = title_margin + pt_to_mm * text_size)),
    axis.text.y = element_text(size = text_size, margin = margin(r = text_margin)),
    axis.line = element_line(color = "black", linewidth = 2)
  ) +

  scale_y_continuous(
    limits = c(0, 80),
    breaks = seq(0, 80, by = 20)
  ) +

  scale_x_continuous(
    breaks = c(1, 2, 3, 4, 5, 6),
    labels = c("O2", "O3", "O4", "O6", "O7", "O8")
  ) +
  
   # Uncertain: open box
  annotate(
    "rect",
    xmin = legend_x1 - legend_box_w / 3,
    xmax = legend_x1 + legend_box_w,
    ymin = legend_y - legend_box_h / 2,
    ymax = legend_y + legend_box_h / 2,
    fill = "white",
    color = "black",
    linewidth = 1.2
  ) +
  annotate(
    "text",
    x = legend_x1 + legend_box_w + legend_text_gap,
    y = legend_y,
    label = "Uncertain",
    hjust = 0,
    size = legend_text_size
  ) +

  # Certain: white box with diagonal lines
  annotate(
    "rect",
    xmin = legend_x2 - legend_box_w / 3,
    xmax = legend_x2 + legend_box_w,
    ymin = legend_y - legend_box_h / 2,
    ymax = legend_y + legend_box_h / 2,
    fill = "white",
    color = "black",
    linewidth = 1.2
  ) +
  annotate(
    "segment",
    x = legend_x2 - legend_box_w / 3 + legend_line_offset_1,
    xend = legend_x2 - legend_box_w / 3 + legend_line_offset_1 + legend_line_w,
    y = legend_y - legend_line_y,
    yend = legend_y + legend_line_y,
    color = "grey35",
    linewidth = 2.2
  ) +
  annotate(
    "segment",
    x = legend_x2 - legend_box_w / 3 + legend_line_offset_2,
    xend = legend_x2 - legend_box_w / 3 + legend_line_offset_2 + legend_line_w,
    y = legend_y - legend_line_y,
    yend = legend_y + legend_line_y,
    color = "grey35",
    linewidth = 2.2
  ) +
  
  annotate(
    "text",
    x = legend_x2 + legend_box_w + legend_text_gap,
    y = legend_y,
    label = "Certain",
    hjust = 0,
    size = legend_text_size
  ) +

  coord_cartesian(ylim = c(0, 88), clip = "off") +
  theme(
    legend.position = "none",
    plot.margin = margin(18, 8, 6, 6)
  )

ggsave(
  ".\\02_fig\\02_situation_diff_bar_EXP2-2_CMPD_260607.svg",
  plot = p2,
  width = width_in_inches,
  height = height_in_inches,
  units = "in"
)

```

## fig-Allocation
```{r, echo=TRUE}
certain_palette <- c(
  "Outcome2" = "#D6E6F5",
  "Outcome3" = "#DCEBDD",
  "Outcome4" = "#E6E8C8",
  "Outcome6" = "#F1D8B8",
  "Outcome7" = "#F2BE9E",
  "Outcome8" = "#E99A78"
)

uncertain_palette <- c(
  "Outcome2" = "#4F81BD",
  "Outcome3" = "#6FA56F",
  "Outcome4" = "#9BA96A",
  "Outcome6" = "#C79A5A",
  "Outcome7" = "#D9845F",
  "Outcome8" = "#E76F51"
)



legend_y <- 78
legend_x1 <- 1.25
legend_x2 <- 3.65

legend_box_w <- 0.42
legend_box_h <- 4.0
legend_text_gap <- 0.2
legend_text_size <- legend_size / 2.4

legend_line_offset_1 <- 0.04
legend_line_offset_2 <- 0.20
legend_line_w <- 0.18
legend_line_y <- 1.45

exp_data$Outcome_raw <- factor(exp_data$Outcome_raw, 
                        levels = c("Outcome2","Outcome3", "Outcome4","Outcome6","Outcome7","Outcome8"))
exp_data$Situation_raw <- factor(exp_data$Situation_raw, levels = c("Uncertain", "Certain"))

# 先分开处理两个组的数据
df_u <- subset(exp_data, Situation_raw == "Uncertain")
df_c <- subset(exp_data, Situation_raw == "Certain")


exp_data$x_pos = as.numeric(exp_data$Outcome_raw) + ifelse(exp_data$Situation_raw == "Uncertain", -drift, drift)

summary_data_all <- exp_data %>%
  group_by(Situation_raw, Outcome_raw) %>%
  summarize(
    mean_value = mean(Value, na.rm = TRUE),
    se = sd(Value, na.rm = TRUE) / sqrt(sum(!is.na(Value))),
    .groups = "drop"
  ) %>%
  mutate(
    x_pos = as.numeric(Outcome_raw) +
      ifelse(Situation_raw == "Uncertain", -drift, drift),
    fill_color = case_when(
      Situation_raw == "Uncertain" ~ unname(uncertain_palette[as.character(Outcome_raw)]),
      Situation_raw == "Certain" ~ unname(certain_palette[as.character(Outcome_raw)])
    )
  )

sig1_y <- 70
sig2_y <- 70
sig3_y <- 74
sig_seg_margin <- 0.6
sig_interval <- 0.02
sig_height <- 1

drift <- 0.18

pattern_angle <- 45
pattern_density <- 0.40
pattern_spacing <- 0.07
pattern_size <- 0.20

p2 <- ggplot() +
  geom_col(
  data = summary_data_all,
  aes(
    x = x_pos,
    y = mean_value,
    fill = fill_color
  ),
  width = bar_width,
  color = NA
) +
scale_fill_identity() +
  
  # geom_point(
  #   data = exp_data,
  #   aes(x = x_pos, group = Outcome_raw, y = Value, color = Outcome_raw),
  #   size = point_size,
  #   alpha = point_alpha,
  #   position = position_dodge(bar_width),
  #   show.legend = FALSE
  # ) +

  geom_errorbar(
    data = summary_data_all,
    aes(
      x = x_pos,
      ymin = mean_value - se,
      ymax = mean_value + se
    ),
    width = 0.1,
    linewidth = 1.5
  ) +
  # scale_fill_identity() +
  # scale_color_manual(values = outcome_palette, guide = "none") +
  # scale_color_manual(values = f_outcome_edge) +
  # scale_fill_manual(values = f_outcome_fill) +
  # scale_pattern_fill_manual(values = outcome_palette, guide = "none") +
  # scale_pattern_colour_manual(values = outcome_palette, guide = "none") +

  # scale_pattern_manual(
  #   values = c(
  #     "Uncertain" = "none",
  #     "Certain" = "stripe"
  #   ),
  #   name = NULL
  # ) +


  xlab("Outcome") +
  ylab("Allocation") +

  theme_classic(base_family = "Arial") +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.justification = "center",
    legend.title = element_blank(),
    legend.text = element_text(size = legend_size, color = "black"),
    legend.key.width = unit(1.2, "cm"),
    legend.key.height = unit(0.45, "cm"),
    legend.box.margin = margin(b = 4),

    axis.title.x = element_text(size = title_size, margin = margin(t = title_margin)),
    axis.text.x = element_text(size = text_x_size, margin = margin(t = text_margin)),
    axis.title.y = element_text(size = title_size, margin = margin(r = title_margin + pt_to_mm * text_size)),
    axis.text.y = element_text(size = text_size, margin = margin(r = text_margin)),
    axis.line = element_line(color = "black", linewidth = 2)
  ) +

  scale_y_continuous(
    limits = c(0, 80),
    breaks = seq(0, 80, by = 20)
  ) +

  scale_x_continuous(
    breaks = c(1, 2, 3, 4, 5, 6),
    labels = c("O2", "O3", "O4", "O6", "O7", "O8")
  ) +
  
   # Uncertain: open box
  annotate(
    "rect",
    xmin = legend_x1 - legend_box_w / 3,
    xmax = legend_x1 + legend_box_w,
    ymin = legend_y - legend_box_h / 2,
    ymax = legend_y + legend_box_h / 2,
    fill = "white",
    color = "black",
    linewidth = 1.2
  ) +
  annotate(
    "text",
    x = legend_x1 + legend_box_w + legend_text_gap,
    y = legend_y,
    label = "Uncertain",
    hjust = 0,
    size = legend_text_size
  ) +

  # Certain: white box with diagonal lines
  annotate(
    "rect",
    xmin = legend_x2 - legend_box_w / 3,
    xmax = legend_x2 + legend_box_w,
    ymin = legend_y - legend_box_h / 2,
    ymax = legend_y + legend_box_h / 2,
    fill = "white",
    color = "black",
    linewidth = 1.2
  ) +
  annotate(
    "segment",
    x = legend_x2 - legend_box_w / 3 + legend_line_offset_1,
    xend = legend_x2 - legend_box_w / 3 + legend_line_offset_1 + legend_line_w,
    y = legend_y - legend_line_y,
    yend = legend_y + legend_line_y,
    color = "grey35",
    linewidth = 2.2
  ) +
  annotate(
    "segment",
    x = legend_x2 - legend_box_w / 3 + legend_line_offset_2,
    xend = legend_x2 - legend_box_w / 3 + legend_line_offset_2 + legend_line_w,
    y = legend_y - legend_line_y,
    yend = legend_y + legend_line_y,
    color = "grey35",
    linewidth = 2.2
  ) +
  
  annotate(
    "text",
    x = legend_x2 + legend_box_w + legend_text_gap,
    y = legend_y,
    label = "Certain",
    hjust = 0,
    size = legend_text_size
  ) +

  coord_cartesian(ylim = c(0, 88), clip = "off") +
  theme(
    legend.position = "none",
    plot.margin = margin(18, 8, 6, 6)
  )

ggsave(
  ".\\02_fig\\02_situation_diff_bar_EXP2-2_CMPD_260607.svg",
  plot = p2,
  width = width_in_inches,
  height = height_in_inches,
  units = "in"
)

```


# Gratitude
```{r EXP3_PMPD Allocation}
# 读取 Excel 文件
data <- read_excel(data_dir, sheet = 'Gratitude')


#### 提取risky下三个情境的Gratitude/Allocation
exp_data <- data[data$Outcome_d == 'HigherOutcome',]

tmp_data <- data[data$Outcome_d == 'LowerOutcome',]
exp_data <- rbind(exp_data, tmp_data)

# tmp_data <- data[data$Outcome == 'Uncertain',]
# exp_data <- rbind(exp_data, tmp_data)
####

### one-factor ANOVA
print('【Exp3】')

# 使用tapply计算平均值和标准差
means <- tapply(exp_data$Value, list(exp_data$Outcome_raw, exp_data$Situation_raw), mean)
std_devs <- tapply(exp_data$Value, list(exp_data$Outcome_raw, exp_data$Situation_raw), sd)
cat("Means:", means, '\n')
cat("Standard Deviations:", std_devs, '\n')

```

```{r}
# 执行单因素方差分析
MANOVA(
  exp_data, dv = "Value", subID = "SubID", within = c("Outcome_raw","Situation_raw"), sph.correction = 'GG') %>%
  EMMEANS(effect = "Outcome_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Situation_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Outcome_raw", by = "Situation_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Situation_raw", by = "Outcome_raw", p.adjust = "bonferroni")

```



## fig-Gratitude
```{r, echo=TRUE}

exp_data$Outcome_raw <- factor(exp_data$Outcome_raw, 
                        levels = c("Outcome2","Outcome3", "Outcome4","Outcome6","Outcome7","Outcome8"))
exp_data$Situation_raw <- factor(exp_data$Situation_raw, levels = c("Uncertain", "Certain"))

# 先分开处理两个组的数据
df_u <- subset(exp_data, Situation_raw == "Uncertain")
df_c <- subset(exp_data, Situation_raw == "Certain")

# 计算每组的平均值和标准误差
summary_data_u <- df_u %>%
  group_by(Outcome_raw) %>%
  summarize(mean_value = mean(Value,na.rm=T), se = sd(Value) / sqrt(length(Value)))

# 计算每组的平均值和标准误差
summary_data_c <- df_c %>%
  group_by(Outcome_raw) %>%
  summarize(mean_value = mean(Value,na.rm=T), se = sd(Value) / sqrt(length(Value)))


sig1_y <- 70
sig2_y <- 70
sig3_y <- 74
sig_seg_margin <- 0.6
sig_interval <- 0.02
sig_height <- 1

drift <- 0.18

p2 <- ggplot()+
  # 绘制条形图和标准误差
  geom_bar(data = summary_data_u, stat = "identity", 
           aes(x = as.numeric(Outcome_raw)-drift, y = mean_value, fill = Outcome_raw), 
           width = bar_width) +

  scale_fill_manual(values = c("#FFD06F", "#FFC26A", "#FFB466", "#F9A161", "#F18F5B", "#E76254")) +

  geom_errorbar(data = summary_data_u, 
                aes(x = as.numeric(Outcome_raw) - drift, ymin = mean_value - se, ymax = mean_value + se),
               width = 0.1,  size = 1.5) +  # 与条形图对齐
  
  geom_bar(data = summary_data_c, stat = "identity", 
           aes(x = as.numeric(Outcome_raw) + drift, y = mean_value, color = Outcome_raw), fill = NA, 
           width = bar_width, linewidth = 3) +

  scale_color_manual(values = c("#FFD06F", "#FFC26A", "#FFB466", "#F9A161", "#F18F5B", "#E76254")) +

  geom_errorbar(data = summary_data_c, 
                aes(x = as.numeric(Outcome_raw) + drift, ymin = mean_value - se, ymax = mean_value + se),
               width = 0.1, size = 1.5) +  # 与条形图对齐

  xlab("Gratitude") + #横坐标名称
  ylab("Allocation") + #纵坐标名称
  theme_classic() +  #去掉背景灰色
  theme(
    axis.title.x = element_text(size = title_x_size, margin = margin(t = title_margin)),
    axis.text.x = element_text(size = text_x_size, margin = margin(t = text_margin)),
    axis.title.y = element_text(size = title_y_size, margin = margin(r = title_margin)),
    axis.text.y = element_text(size = text_y_size,margin = margin(r = text_margin)),
    axis.line = element_line(color = "black", linewidth = 2)) +
  # guides(
  #   fill = guide_legend(
  #     keywidth = unit(2, "cm"),
  #     title = NULL)
  # ) +
  theme(
    legend.position = "none"
#     legend.position = c(0.5, 0.95),  # (x=0~1, y=0~1) 从左下角为 (0,0),
#     legend.direction = "horizontal",
# #     legend.spacing.x = unit(0.8, "cm"),
#     legend.key.width = unit(2.4, "cm"),
#     legend.title = element_blank(),
#     legend.text  = element_text(size = legend_size, margin = margin(r = 40,l = 10))
  ) +

  scale_y_continuous(limits = c(0, 95), breaks = seq(0, 90, by = 20)) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),labels = c("O2","O3","O4","O6","O7","O8"))
  
# ##########################################################################################
#   geom_segment(aes(x = 1 - bar_width/3 + sig_interval, xend = 1 - sig_interval, y = sig1_y, yend = sig1_y), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 - bar_width/3 + sig_interval, xend = 1 - bar_width/3 + sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 - sig_interval, xend = 1 - sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 1 - bar_width/6, y = sig1_y + sig_seg_margin, label = "**"), 
#             color = "black", size = sig_size) +  # 显著性值
#   
#   geom_segment(aes(x = 1 + sig_interval, xend = 1 + bar_width/3 - sig_interval, y = sig2_y, yend = sig2_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 + sig_interval, xend = 1 + sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 + bar_width/3 - sig_interval, xend = 1 + bar_width/3 - sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 1 + bar_width/6, y = sig2_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
#   
#   geom_segment(aes(x = 1 - bar_width/3 + sig_interval, xend = 1 + bar_width/3 - sig_interval, y = sig3_y, yend = sig3_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 - bar_width/3 + sig_interval, xend = 1 - bar_width/3 + sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 + bar_width/3 - sig_interval, xend = 1 + bar_width/3 - sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_text(aes(x = 1, y = sig3_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
# 
# ##########################################################################################
# 
#   geom_segment(aes(x = 2 - bar_width/3 + sig_interval, xend = 2 - sig_interval, y = sig1_y, yend = sig1_y), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 - bar_width/3 + sig_interval, xend = 2 - bar_width/3 + sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 - sig_interval, xend = 2 - sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 2 - bar_width/6, y = sig1_y + sig_seg_margin, label = "***"), 
#             color = "black", size = sig_size) +  # 显著性值
#   
#   geom_segment(aes(x = 2 + sig_interval, xend = 2 + bar_width/3 - sig_interval, y = sig2_y, yend = sig2_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 + sig_interval, xend = 2 + sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 + bar_width/3 - sig_interval, xend = 2 + bar_width/3 - sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 2 + bar_width/6, y = sig2_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
#   geom_segment(aes(x = 2 - bar_width/3 + sig_interval, xend = 2 + bar_width/3 - sig_interval, y = sig3_y, yend = sig3_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 - bar_width/3 + sig_interval, xend = 2 - bar_width/3 + sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 + bar_width/3 - sig_interval, xend = 2 + bar_width/3 - sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_text(aes(x = 2, y = sig3_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
# ##########################################################################################
# 
#   geom_segment(aes(x = 3 - bar_width/3 + sig_interval, xend = 3 - sig_interval, y = sig1_y, yend = sig1_y), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 - bar_width/3 + sig_interval, xend = 3 - bar_width/3 + sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 - sig_interval, xend = 3 - sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 3 - bar_width/6, y = sig1_y + sig_seg_margin, label = "***"), 
#             color = "black", size = sig_size) +  # 显著性值
#   
#   geom_segment(aes(x = 3 + sig_interval, xend = 3 + bar_width/3 - sig_interval, y = sig2_y, yend = sig2_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 + sig_interval, xend = 3 + sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 + bar_width/3 - sig_interval, xend = 3 + bar_width/3 - sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 3 + bar_width/6, y = sig2_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
#   geom_segment(aes(x = 3 - bar_width/3 + sig_interval, xend = 3 + bar_width/3 - sig_interval, y = sig3_y, yend = sig3_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 - bar_width/3 + sig_interval, xend = 3 - bar_width/3 + sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 + bar_width/3 - sig_interval, xend = 3 + bar_width/3 - sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_text(aes(x = 3, y = sig3_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) # 显著性值
##########################################################################################

# ggsave(".\\results\\exp3_alloc_avova_241226.pdf", device = cairo_pdf, plot = p2, width = width_in_inches, height = height_in_inches, units = "in")
ggsave(".\\02_fig\\02_grati_situation_diff_bar_EXP2-2_CMPD_260128.svg", plot = p2, 
       width = width_in_inches, height = height_in_inches, units = "in")

```



# Intention
```{r EXP3_PMPD Allocation}
# 读取 Excel 文件
data <- read_excel(data_dir, sheet = 'Intention')


#### 提取risky下三个情境的Gratitude/Allocation
exp_data <- data[data$Outcome_d == 'HigherOutcome',]

tmp_data <- data[data$Outcome_d == 'LowerOutcome',]
exp_data <- rbind(exp_data, tmp_data)

# tmp_data <- data[data$Outcome == 'Uncertain',]
# exp_data <- rbind(exp_data, tmp_data)
####

### one-factor ANOVA
print('【Exp3】')

# 使用tapply计算平均值和标准差
means <- tapply(exp_data$Value, list(exp_data$Outcome_raw, exp_data$Situation_raw), mean)
std_devs <- tapply(exp_data$Value, list(exp_data$Outcome_raw, exp_data$Situation_raw), sd)
cat("Means:", means, '\n')
cat("Standard Deviations:", std_devs, '\n')

```

```{r}
# 执行单因素方差分析
MANOVA(
  exp_data, dv = "Value", subID = "SubID", within = c("Outcome_raw","Situation_raw"), sph.correction = 'GG') %>%
  EMMEANS(effect = "Outcome_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Situation_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Outcome_raw", by = "Situation_raw", p.adjust = "bonferroni") %>%
  EMMEANS(effect = "Situation_raw", by = "Outcome_raw", p.adjust = "bonferroni")

```

## fig-Intention
```{r, echo=TRUE}

exp_data$Outcome_raw <- factor(exp_data$Outcome_raw, 
                        levels = c("Outcome2","Outcome3", "Outcome4","Outcome6","Outcome7","Outcome8"))
exp_data$Situation_raw <- factor(exp_data$Situation_raw, levels = c("Uncertain", "Certain"))

# 先分开处理两个组的数据
df_u <- subset(exp_data, Situation_raw == "Uncertain")
df_c <- subset(exp_data, Situation_raw == "Certain")

# 计算每组的平均值和标准误差
summary_data_u <- df_u %>%
  group_by(Outcome_raw) %>%
  summarize(mean_value = mean(Value,na.rm=T), se = sd(Value) / sqrt(length(Value)))

# 计算每组的平均值和标准误差
summary_data_c <- df_c %>%
  group_by(Outcome_raw) %>%
  summarize(mean_value = mean(Value,na.rm=T), se = sd(Value) / sqrt(length(Value)))


sig1_y <- 70
sig2_y <- 70
sig3_y <- 74
sig_seg_margin <- 0.6
sig_interval <- 0.02
sig_height <- 1

drift <- 0.18

p2 <- ggplot()+
  # 绘制条形图和标准误差
  geom_bar(data = summary_data_u, stat = "identity", 
           aes(x = as.numeric(Outcome_raw)-drift, y = mean_value, fill = Outcome_raw), 
           width = bar_width) +

  scale_fill_manual(values = c("#FFD06F", "#FFC26A", "#FFB466", "#F9A161", "#F18F5B", "#E76254")) +

  geom_errorbar(data = summary_data_u, 
                aes(x = as.numeric(Outcome_raw) - drift, ymin = mean_value - se, ymax = mean_value + se),
               width = 0.1,  size = 1.5) +  # 与条形图对齐
  
  geom_bar(data = summary_data_c, stat = "identity", 
           aes(x = as.numeric(Outcome_raw) + drift, y = mean_value, color = Outcome_raw), fill = NA, 
           width = bar_width, linewidth = 3) +

  scale_color_manual(values = c("#FFD06F", "#FFC26A", "#FFB466", "#F9A161", "#F18F5B", "#E76254")) +

  geom_errorbar(data = summary_data_c, 
                aes(x = as.numeric(Outcome_raw) + drift, ymin = mean_value - se, ymax = mean_value + se),
               width = 0.1, size = 1.5) +  # 与条形图对齐

  xlab("Intention") + #横坐标名称
  ylab("Intention") + #纵坐标名称
  theme_classic() +  #去掉背景灰色
  theme(
    axis.title.x = element_text(size = title_x_size, margin = margin(t = title_margin)),
    axis.text.x = element_text(size = text_x_size, margin = margin(t = text_margin)),
    axis.title.y = element_text(size = title_y_size, margin = margin(r = title_margin)),
    axis.text.y = element_text(size = text_y_size,margin = margin(r = text_margin)),
    axis.line = element_line(color = "black", linewidth = 2)) +
  # guides(
  #   fill = guide_legend(
  #     keywidth = unit(2, "cm"),
  #     title = NULL)
  # ) +
  theme(
    legend.position = "none"
#     legend.position = c(0.5, 0.95),  # (x=0~1, y=0~1) 从左下角为 (0,0),
#     legend.direction = "horizontal",
# #     legend.spacing.x = unit(0.8, "cm"),
#     legend.key.width = unit(2.4, "cm"),
#     legend.title = element_blank(),
#     legend.text  = element_text(size = legend_size, margin = margin(r = 40,l = 10))
  ) +

  scale_y_continuous(limits = c(0, 95), breaks = seq(0, 90, by = 20)) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),labels = c("O2","O3","O4","O6","O7","O8"))
  
# ##########################################################################################
#   geom_segment(aes(x = 1 - bar_width/3 + sig_interval, xend = 1 - sig_interval, y = sig1_y, yend = sig1_y), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 - bar_width/3 + sig_interval, xend = 1 - bar_width/3 + sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 - sig_interval, xend = 1 - sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 1 - bar_width/6, y = sig1_y + sig_seg_margin, label = "**"), 
#             color = "black", size = sig_size) +  # 显著性值
#   
#   geom_segment(aes(x = 1 + sig_interval, xend = 1 + bar_width/3 - sig_interval, y = sig2_y, yend = sig2_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 + sig_interval, xend = 1 + sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 + bar_width/3 - sig_interval, xend = 1 + bar_width/3 - sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 1 + bar_width/6, y = sig2_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
#   
#   geom_segment(aes(x = 1 - bar_width/3 + sig_interval, xend = 1 + bar_width/3 - sig_interval, y = sig3_y, yend = sig3_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 - bar_width/3 + sig_interval, xend = 1 - bar_width/3 + sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 1 + bar_width/3 - sig_interval, xend = 1 + bar_width/3 - sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_text(aes(x = 1, y = sig3_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
# 
# ##########################################################################################
# 
#   geom_segment(aes(x = 2 - bar_width/3 + sig_interval, xend = 2 - sig_interval, y = sig1_y, yend = sig1_y), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 - bar_width/3 + sig_interval, xend = 2 - bar_width/3 + sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 - sig_interval, xend = 2 - sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 2 - bar_width/6, y = sig1_y + sig_seg_margin, label = "***"), 
#             color = "black", size = sig_size) +  # 显著性值
#   
#   geom_segment(aes(x = 2 + sig_interval, xend = 2 + bar_width/3 - sig_interval, y = sig2_y, yend = sig2_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 + sig_interval, xend = 2 + sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 + bar_width/3 - sig_interval, xend = 2 + bar_width/3 - sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 2 + bar_width/6, y = sig2_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
#   geom_segment(aes(x = 2 - bar_width/3 + sig_interval, xend = 2 + bar_width/3 - sig_interval, y = sig3_y, yend = sig3_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 - bar_width/3 + sig_interval, xend = 2 - bar_width/3 + sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 2 + bar_width/3 - sig_interval, xend = 2 + bar_width/3 - sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_text(aes(x = 2, y = sig3_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
# ##########################################################################################
# 
#   geom_segment(aes(x = 3 - bar_width/3 + sig_interval, xend = 3 - sig_interval, y = sig1_y, yend = sig1_y), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 - bar_width/3 + sig_interval, xend = 3 - bar_width/3 + sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 - sig_interval, xend = 3 - sig_interval, 
#                    y = sig1_y, yend = sig1_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 3 - bar_width/6, y = sig1_y + sig_seg_margin, label = "***"), 
#             color = "black", size = sig_size) +  # 显著性值
#   
#   geom_segment(aes(x = 3 + sig_interval, xend = 3 + bar_width/3 - sig_interval, y = sig2_y, yend = sig2_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 + sig_interval, xend = 3 + sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 + bar_width/3 - sig_interval, xend = 3 + bar_width/3 - sig_interval, 
#                    y = sig1_y, yend = sig2_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   
#   geom_text(aes(x = 3 + bar_width/6, y = sig2_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) + # 显著性值
#   geom_segment(aes(x = 3 - bar_width/3 + sig_interval, xend = 3 + bar_width/3 - sig_interval, y = sig3_y, yend = sig3_y),
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 - bar_width/3 + sig_interval, xend = 3 - bar_width/3 + sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_segment(aes(x = 3 + bar_width/3 - sig_interval, xend = 3 + bar_width/3 - sig_interval, 
#                    y = sig3_y, yend = sig3_y - sig_height), 
#                color = "black", size = sig_seg_size) +  # 显著性
#   geom_text(aes(x = 3, y = sig3_y + sig_seg_margin, label = "***"),
#             color = "black", size = sig_size) # 显著性值
##########################################################################################

# ggsave(".\\results\\exp3_alloc_avova_241226.pdf", device = cairo_pdf, plot = p2, width = width_in_inches, height = height_in_inches, units = "in")
ggsave(".\\02_fig\\02_intent_situation_diff_bar_EXP2-2_CMPD_260128.svg", plot = p2, 
       width = width_in_inches, height = height_in_inches, units = "in")

```
